sonar.projectKey=chrrodri_learn-jenkins-app
sonar.organization=chrrodri

# Código fuente
sonar.sources=src
#sonar.tests=src

# Servidor SonarCloud
sonar.host.url=https://sonarcloud.io

# Excluir carpetas generadas
sonar.exclusions=node_modules/**,build/**,coverage/**